import type { Metadata } from 'next'
import './globals.css'
import { Inter } from 'next/font/google'
import ClientLayout from './client-layout'
import AuthCheck from "@/app/components/auth-check"
import { db } from './firebase/config'
import { auth } from './firebase/config'
const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: '呑恋 -nomikoi-',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
}

export default function RootLayout({children,}: Readonly<{children: React.ReactNode}>) {


  if (auth === null) {

  }
  return (
    <html lang="ja">
      <body className={`${inter.className} default-bg overscroll-none`}>
        <AuthCheck>
          
          <ClientLayout>{children}</ClientLayout>
        </AuthCheck>
      </body>
    </html>
  )
}

